---
# Create a PersistentVolume called custom-volume with size: 50MiB
# reclaim policy:retain, Access Modes: ReadWriteMany and hostPath: /opt/data

apiVersion: v1
kind: PersistentVolume
metadata:
  name: custom-volume
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/data
