---
# Apply a label app_type=beta to node controlplane.
# Create a new deployment called beta-apps with image: nginx and replicas: 3.
# Set Node Affinity to the deployment to place the PODs on controlplane only.
# NodeAffinity: requiredDuringSchedulingIgnoredDuringExecution

# kubectl edit nodes controlplane

apiVersion: apps/v1
kind: Deployment
metadata:
  name: beta-apps
spec:
  selector:
    matchLabels:
      app: beta-apps
  replicas: 3
  template:
    metadata:
      labels:
        app: beta-apps
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app_type
                    operator: In
                    values:
                      - beta
      containers:
      - name: beta-apps
        image: nginx
