---
# Create a new pod called nginx1401 in the default namespace with the image nginx.
# Add a livenessProbe to the container to restart it if the command ls /var/www/html/probe fails.
# This check should start after a delay of 10 seconds and run every 60 seconds.

# You may delete and recreate the object. Ignore the warnings from the probe.

apiVersion: v1
kind: Pod
metadata:
  name: nginx1401
spec:
  containers:
  - name: nginx1401
    image: nginx
    livenessProbe:
      exec:
        command:
          - ls
          - /var/www/html/probe
      initialDelaySeconds: 10
      periodSeconds: 60
