---
# We have deployed a new pod called pod-with-rprobe. This Pod has an initial delay before it is Ready.
# Update the newly created pod pod-with-rprobe with a readinessProbe using the given spec

# httpGet path: /ready
# httpGet port: 8080

apiVersion: v1
kind: Pod
metadata:
  labels:
    name: pod-with-rprobe
  name: pod-with-rprobe
spec:
  containers:
  - env:
    - name: APP_START_DELAY
      value: "180"
    image: kodekloud/webapp-delayed-start
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
    imagePullPolicy: Always
    name: pod-with-rprobe
    ports:
    - containerPort: 8080
      protocol: TCP
