apiVersion: batch/v1
kind: CronJob
metadata:
  name: reporting-cron.job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      completions: 3
      parallelism: 3
      template:
        spec:
          containers:
          - name: math-add
            image: ubuntu
            command: ["expre", "2", "+", "3"]
          restartPolicy: Never
