---
# We have deployed a few pods in this cluster in various namespaces.
# Inspect them and identify the pod which is not in a Ready state.
# Troubleshoot and fix the issue.

# Next, add a check to restart the container on the same pod if the command ls /var/www/html/file_check fails.
# This check should start after a delay of 10 seconds and run every 60 seconds.

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx1401
  namespace: dev1401
spec:
  containers:
  - image: kodekloud/nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 9080
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 9080
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    livenessProbe:
      failureThreshold: 3
      exec:
        command:
        - ls
        - /var/www/html/file_check
      periodSeconds: 60
      initialDelaySeconds: 10
