apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer-service
spec:
  selector:
    company: KodeKloud
    component: nginx
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
