---
# Update pod app-sec-kff3345 to run as Root user and with the SYS_TIME capability.

# Pod Name: app-sec-kff3345
# Image Name: ubuntu
# SecurityContext: Capability SYS_TIME

apiVersion: v1
kind: Pod
metadata:
  name: app-sec-kff3345
spec:
  securityContext:
    runAsUser: 0
  containers:
  - command:
    - sleep
    - "4800"
    image: ubuntu
    name: ubuntu
    securityContext:
      capabilities:
        add:
          - SYS_TIME

# kubectl delete pod app-sec --force
# kubectl apply -f app-sec.yml

# Alternatively: kubectl replace -f app-sec.yml --force
