---
# Create a Pod called sega with two containers:

# Container 1: Name tails with image busybox and command: sleep 3600.
# Container 2: Name sonic with image nginx and Environment variable: NGINX_PORT with the value 8080.
apiVersion: v1
kind: Pod
metadata:
  name: sega
spec:
  containers:
  - name: tails
    image: busybox
    command:
      - sleep
      - "3600"
  - name: sonic
    image: nginx
    env:
      - name: NGINX_PORT
        value: "8080"

# kubectl apply -f sega.yml
