---
# Create a redis deployment using the image redis:alpine with 1 replica and label app=redis.
# Expose it via a ClusterIP service called redis on port 6379.
# Create a new Ingress Type NetworkPolicy called redis-access which allows only the pods with label access=redis to access the deployment.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine

# kubectl apply -f redis-deploy.yml
# kubectl expose deployment redis --port=6379 --name redis

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-access
spec:
  podSelector:
    matchLabels:
      app: redis
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              access: redis
      ports:
        - protocol: TCP
          port: 6379

# kubectl apply -f redis-access.yml
