apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command:
      - sleep
      - "3600"
    securityContext:
      runAsUser: 1000
      capabilities:
        add:
          - MAC_ADMIN
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
      requests:
        memory: "64Mi"
        cpu: "50m"
