apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-sa

---

apiVersion: v1
kind: Secret
type: kubernetes.uio/service-account-token
metadata:
  name: mysecretname
  annotations:
    kubernetes/io.service-account.name: dashboard-sa

---

apiVersion: v1
kind: Pod
metadata:
  name: my-kubernetes-dashboard
spec:
  serviceAccountName: dashboard-sa
  containers:
  - name: my-kubernetes-dashboard
    image: my-kubernetes-dashboard
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
      requests:
        memory: "64Mi"
        cpu: "50m"
