---
# Create a Redis Deployment

# Create a deployment in the default namespace with the following specifications:

# Name: redis
# Image: redis:alpine
# Replicas: 1
# Labels: app=redis
# CPU Request: 0.2 CPU (200m)
# Container Port: 6379

# Volumes:

# An emptyDir volume named data, mounted at /redis-master-data.
# A ConfigMap volume named redis-config, mounted at /redis-master.
# The ConfigMap has already been created for you. Do not create it again.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        resources:
          requests:
            cpu: "200m"
        ports:
        - containerPort: 6379
        volumeMounts:
          - name: data
            mountPath: /redis-master-data
          - name: redis-config
            mountPath: /redis-master
      volumes:
      - name: data
        emptyDir: {}
      - name: redis-config
        configMap:
          name: redis-config
