# Create a pod named time-check in the dvl1987 namespace.
# This pod should execute a container called time-check using the busybox image.

# Create a ConfigMap named time-config with the data TIME_FREQ=10 in the same namespace.
# The time-check container must run the command: while true; do date; sleep $TIME_FREQ; done,
# directing the output to the file located at /opt/time/time-check.log.
# Ensure that the path /opt/time within the pod mounts a volume that persists for the duration of the pod's lifecycle.
---
apiversion: v1
kind: Namespace
metadata:
  name: dvl1987
spec: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: time-config
  namespace: dvl1987
data:
  TIME_FREQ: "10"
---
apiVersion: v1
kind: Pod
metadata:
  name: time-check
  namespace: dvl1987
spec:
  containers:
  - name: time-check
    image: busybox
    command:
      - /bin/sh
      - -c
      - "while true; do date; sleep $TIME_FREQ; done"
      - "> /opt/time/time-check.log"
    env:
      - name: TIME_FREQ
        valueFrom:
          configMapKeyRef:
            name: time-config
            key: TIME_FREQ
    volumeMounts:
      - name: time-volume
        mountPath: /opt/time
  volumes:
    - name: time-volume
      hostPath:
        path: /data
        type: DirectoryOrCreate
